version: "3.9"
services:
  backend:
    build: ./backend
    container_name: aqua-backend
    network_mode: host
    depends_on:
      - postgres
      - nginx
      - frontend
    volumes:
      - ./backend:/aqua
    environment:
      JWT_SECRET: mega-secret
      POSTGRES_DATABASE: aqua
      POSTGRES_USERNAME: aqua
      POSTGRES_PASSWORD: aqua

    command: ["ash", "./scripts/start.sh"]
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: aqua-frontend
    volumes:
      - ./frontend:/aqua
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: aqua-nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/aqua
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: aqua-postgres
    network_mode: host
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aqua
      POSTGRES_USER: aqua
      POSTGRES_PASSWORD: aqua
    restart: unless-stopped

volumes:
  db: null
