version: "3.9"
services:
  aqua:
    build: .
    container_name: aqua-app
    network_mode: host
    depends_on:
      - postgres
      - nginx
    volumes:
      - .:/aqua
    command: ["uvicorn", "src.entrypoint.presentation.main:app"]
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: aqua-postgres
    network_mode: host
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aqua
      POSTGRES_USER: aqua
      POSTGRES_PASSWORD: aqua
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: aqua-nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

volumes:
  db: null
