version: "3.9"
services:
  app:
    build: .
    container_name: aqua-app
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - .:/aqua
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: aqua-nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
