class DomainError(Exception): ...


class NoWater(DomainError): ...


class NoWeight(DomainError): ...


class NoWeightForWaterBalance(DomainError): ...


class ExtremeWeightForWaterBalance(DomainError): ...
