class DomainError(Exception): ...


class ExtremeUsernameLength(DomainError): ...


class WeekPassword(DomainError): ...


class TooLongPassword(DomainError): ...


class ExtremePasswordHashLength(DomainError): ...


class NotUTCExpirationDate(DomainError): ...
