class DomainError(Exception): ...


class EmptyUsername(DomainError): ...


class WeekPassword(DomainError): ...


class EmptyPasswordHash(DomainError): ...


class NotUTCExpirationDate(DomainError): ...
