version: "3.9"
services:
  aqua:
    build: .
    container_name: aqua-backend
    restart: unless-stopped
    command: ["python", "./src/entrypoint/presentation/periphery/api"]
    volumes:
      - .:/aqua
    networks:
      - private-network
    environment:
      AUTH_DEV: true
      AUTH_POSTGRES_DATABASE: auth
      AUTH_POSTGRES_USERNAME: auth
      AUTH_POSTGRES_PASSWORD: auth
      AUTH_POSTGRES_HOST: auth-postgres
      AUTH_POSTGRES_PORT: 5432
      AUTH_POSTGRES_ECHO: true

      AQUA_DEV: true
      AQUA_MONGO_URI: mongodb://aqua-mongo1,aqua-mongo2,aqua-mongo3/?replicaSet=aquaSet

      ENTRYPOINT_DEV: true

    depends_on:
      - aqua-mongo1
      - aqua-mongo2
      - aqua-mongo3
      - auth-postgres

  aqua-mongo1:
    image: mongo:8.0.3-noble
    container_name: aqua-mongo1
    restart: unless-stopped
    command: --replSet aquaSet --syslog
    volumes:
      - aqua-mongo1-data:/data/db
      - ./scripts/aqua-mongo1:/scripts
    networks:
      - private-network
    depends_on:
      - aqua-mongo2
      - aqua-mongo3

  aqua-mongo2:
    image: mongo:8.0.3-noble
    container_name: aqua-mongo2
    restart: unless-stopped
    command: --replSet aquaSet --syslog
    volumes:
      - aqua-mongo2-data:/data/db
    networks:
      - private-network

  aqua-mongo3:
    image: mongo:8.0.3-noble
    container_name: aqua-mongo3
    restart: unless-stopped
    command: --replSet aquaSet --syslog
    volumes:
      - aqua-mongo3-data:/data/db
    networks:
      - private-network

  auth-postgres:
    image: postgres:16.3-alpine3.19
    container_name: auth-postgres
    restart: unless-stopped
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - private-network
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth

  nginx:
    image: nginx:stable-alpine3.19-perl
    container_name: aqua-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - private-network
    ports:
      - 80:80
    depends_on:
      - aqua

networks:
  private-network:
    driver: bridge

volumes:
  aqua-mongo1-data: null
  aqua-mongo2-data: null
  aqua-mongo3-data: null
  auth-postgres-data: null
