version: "3.9"
services:
  aqua:
    build: .
    container_name: aqua-backend
    restart: unless-stopped
    command: ["python", "./src/entrypoint/presentation/periphery/api"]
    volumes:
      - .:/aqua
    networks:
      - private-network
    environment:
      FOR_DEV: true
      POSTGRES_DATABASE: aqua
      POSTGRES_USERNAME: aqua
      POSTGRES_PASSWORD: aqua
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_ECHO: true
      MONGO_URI: mongodb://mongo1,mongo2,mongo3/?replicaSet=aquaSet
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - postgres

  mongo1:
    image: mongo:8.0.3-noble
    container_name: aqua-mongo1
    restart: unless-stopped
    command: --replSet aquaSet
    volumes:
      - mongo1_data:/data/db
      - ./scripts/mongo1:/scripts
    networks:
      - private-network
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    image: mongo:8.0.3-noble
    container_name: aqua-mongo2
    restart: unless-stopped
    command: --replSet aquaSet
    volumes:
      - mongo2_data:/data/db
    networks:
      - private-network

  mongo3:
    image: mongo:8.0.3-noble
    container_name: aqua-mongo3
    restart: unless-stopped
    command: --replSet aquaSet
    volumes:
      - mongo3_data:/data/db
    networks:
      - private-network

  postgres:
    image: postgres:16.3-alpine3.19
    container_name: aqua-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - private-network
    environment:
      POSTGRES_DB: aqua
      POSTGRES_USER: aqua
      POSTGRES_PASSWORD: aqua

  nginx:
    image: nginx:stable-alpine3.19-perl
    container_name: aqua-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - private-network
    ports:
      - 80:80
    depends_on:
      - aqua

networks:
  private-network:
    driver: bridge

volumes:
  mongo1_data: null
  mongo2_data: null
  mongo3_data: null
  postgres_data: null
