"""add `cancelled` to `Session`

Revision ID: 666636fd1237
Revises: 3d120acd8cdc
Create Date: 2024-09-05 17:13:35.624807

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "666636fd1237"
down_revision: Union[str, None] = "3d120acd8cdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("cancelled", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "cancelled")
    # ### end Alembic commands ###
