"""add `next_session_id` to `Session`

Revision ID: 69b6ca49eeda
Revises: e3df1a0f98eb
Create Date: 2024-09-24 08:28:23.751105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "69b6ca49eeda"
down_revision: Union[str, None] = "e3df1a0f98eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("next_session_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "sessions", "sessions", ["next_session_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_column("sessions", "next_session_id")
    # ### end Alembic commands ###
