"""init

Revision ID: f00d68373d9a
Revises:
Create Date: 2024-06-16 14:35:43.352607

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f00d68373d9a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aqua_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("water_balance", sa.Integer(), nullable=False),
        sa.Column("glass", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["auth_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "days",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("real_water_balance", sa.Integer(), nullable=False),
        sa.Column("target_water_balance", sa.Integer(), nullable=False),
        sa.Column("date_", sa.Date(), nullable=False),
        sa.Column("result", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["aqua_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "records",
        sa.Column("drunk_water", sa.Integer(), nullable=False),
        sa.Column("recording_time", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["aqua_users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("records")
    op.drop_table("days")
    op.drop_table("aqua_users")
    op.drop_table("auth_users")
    # ### end Alembic commands ###
