"""add `start_time` to `Session`

Revision ID: f7f0aab015b7
Revises: aa8a8919f3c7
Create Date: 2024-08-19 17:38:28.130859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7f0aab015b7"
down_revision: Union[str, None] = "aa8a8919f3c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "start_time")
    # ### end Alembic commands ###
