"""add `change_time` to `PreviousUsername`

Revision ID: 3d120acd8cdc
Revises: d6c0c3dc2431
Create Date: 2024-09-05 13:31:24.388894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3d120acd8cdc"
down_revision: Union[str, None] = "d6c0c3dc2431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_previous_usernames",
        sa.Column("change_time", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auth_previous_usernames", "change_time")
    # ### end Alembic commands ###
