"""add indexes to `auth` tables

Revision ID: da032010791f
Revises: e039e3403778
Create Date: 2024-10-13 14:54:49.211305

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "da032010791f"
down_revision: Union[str, None] = "e039e3403778"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_auth_account_name_taking_times_account_name_id"),
        "account_name_taking_times",
        ["account_name_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_account_names_account_id"),
        "account_names",
        ["account_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_account_names_text"),
        "account_names",
        ["text"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_sessions_account_id"),
        "sessions",
        ["account_id"],
        unique=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_sessions_account_id"),
        table_name="sessions",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_account_names_text"),
        table_name="account_names",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_account_names_account_id"),
        table_name="account_names",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_auth_account_name_taking_times_account_name_id"),
        table_name="account_name_taking_times",
        schema="auth",
    )
    op.drop_table("account_name_taking_times", schema="auth")
    # ### end Alembic commands ###
