"""add `is_accidental` to `Record`

Revision ID: e3df1a0f98eb
Revises: 666636fd1237
Create Date: 2024-09-06 14:32:04.385574

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e3df1a0f98eb"
down_revision: Union[str, None] = "666636fd1237"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records", sa.Column("is_accidental", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "is_accidental")
    # ### end Alembic commands ###
