"""Split user table for apps

Revision ID: 8f22a14b781d
Revises: 2386e032fadd
Create Date: 2024-06-03 09:42:12.363595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f22a14b781d"
down_revision: Union[str, None] = "2386e032fadd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aqua_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("water_balance", sa.Integer(), nullable=False),
        sa.Column("glass", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["auth_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "water_balance", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("glass", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("weight", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.drop_table("aqua_users")
    op.drop_table("auth_users")
    # ### end Alembic commands ###
