"""fix relationships

Revision ID: b2e15ddd5d13
Revises: 8f22a14b781d
Create Date: 2024-06-03 12:47:15.742689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2e15ddd5d13"
down_revision: Union[str, None] = "8f22a14b781d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "records", "aqua_users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "records", type_="foreignkey")
    op.drop_column("records", "user_id")
    # ### end Alembic commands ###
