"""add day table

Revision ID: f114a12b63c3
Revises: b2e15ddd5d13
Create Date: 2024-06-10 11:34:51.332865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f114a12b63c3"
down_revision: Union[str, None] = "b2e15ddd5d13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "days",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("real_water_balance", sa.Integer(), nullable=False),
        sa.Column("target_water_balance", sa.Integer(), nullable=False),
        sa.Column("date_", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["aqua_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("days")
    # ### end Alembic commands ###
