name: backend.auth

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff
        run: docker compose -f ./services/backend/docker-compose.dev.yml run aqua ruff check src/auth -n

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mypy
        run: docker compose -f ./services/backend/docker-compose.dev.yml run aqua mypy src/auth
