name: Lint Python

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install ruff
        run: pip install ruff

      - name: ruff
        run: python -m ruff check ./backend
