name: Lint Python types

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: mypy
        run: docker compose -f backend/docker-compose.dev.yml run aqua mypy .
