name: Test Python

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: pytest
        run: docker compose -f ./services/backend/docker-compose.dev.yml run aqua pytest
